### ISSUE TITLE
Problem at building phase

### ISSUE THREAD

**Issue by vakexuta** [ph4r05/Whitebox-crypto-AES#12]
When trying to build this project (version 0.4, also with latest sources), remained stuck at some point.
- Debian 8 64-bit OS
- Installed NTL version 9.9.1 (tried too with the default 9.6.2)
  - libntl.a is at /usr/local/lib/libntl.a
  - include libraries at /usr/local/include/NTL/
  - also installed NTL as install-ntl-cached.sh with prefix at $HOME/ntl
  - libntl-dev package NOT installed
- Boost libraries at version 1.55.0

I attach the generated output:

> ./build-debug.sh 
> HOME: /home/user
> NTL_INCLUDE_PATH: /usr/local/include
> NTL_LIB: /usr/local/lib/libntl.a
> -- Boost version: 1.55.0
> -- Found the following Boost libraries:
> --   program_options
> --   serialization
> --   iostreams
> --   random
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/build-debug
> Linking CXX executable main
> /usr/local/lib/libntl.a(lip.o): In function `redc':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:3509: undefined reference to`__gmpn_addmul_1'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:3521: undefined reference to `__gmpn_sub_n'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_rem_struct_basic::eval(long_, void_, _ntl_tmp_vec_)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:5729: undefined reference to `__gmpn_mod_1'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_reduce_struct_montgomery::eval(void__, void__)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:3594: undefined reference to `__gmpn_addmul_1'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:3606: undefined reference to`__gmpn_sub_n'
> /usr/local/lib/libntl.a(lip.o): In function `_ntl_crt_struct_basic::eval(void__, long const_, _ntl_tmp_vec_)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:4703: undefined reference to `__gmpn_addmul_1'
> /usr/local/lib/libntl.a(lip.o): In function`gmod_simple':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:2067: undefined reference to `__gmpn_tdiv_qr'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_rem_struct_fast::eval(long_, void_, _ntl_tmp_vec_)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:5769: undefined reference to `__gmpn_mod_1'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_rem_struct_medium::eval(long_, void_, _ntl_tmp_vec_)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:5813: undefined reference to `__gmpn_mod_1'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_grshift(void_, long, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1420: undefined reference to `__gmpn_rshift'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_glshift(void*, long, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1355: undefined reference to `__gmpn_lshift'
> /usr/local/lib/libntl.a(lip.o): In function`__gmpn_sub':
> /usr/include/x86_64-linux-gnu/gmp.h:2168: undefined reference to `__gmpn_sub_n'
> /usr/local/lib/libntl.a(lip.o): In function`__gmpn_add':
> /usr/include/x86_64-linux-gnu/gmp.h:2129: undefined reference to `__gmpn_add_n'
> /usr/local/lib/libntl.a(lip.o): In function`__gmpn_sub':
> /usr/include/x86_64-linux-gnu/gmp.h:2168: undefined reference to `__gmpn_sub_n'
> /usr/local/lib/libntl.a(lip.o): In function`__gmpn_add':
> /usr/include/x86_64-linux-gnu/gmp.h:2129: undefined reference to `__gmpn_add_n'
> /usr/local/lib/libntl.a(lip.o): In function`__gmpn_sub':
> /usr/include/x86_64-linux-gnu/gmp.h:2168: undefined reference to `__gmpn_sub_n'
> /usr/include/x86_64-linux-gnu/gmp.h:2168: undefined reference to`__gmpn_sub_n'
> /usr/include/x86_64-linux-gnu/gmp.h:2168: undefined reference to `__gmpn_sub_n'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_gmul(void_, void_, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1725: undefined reference to `__gmpn_mul'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1727: undefined reference to`__gmpn_mul'
> /usr/local/lib/libntl.a(lip.o): In function `_ntl_gsmul(void*, long, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1792: undefined reference to `__gmpn_mul_1'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1790: undefined reference to`__gmpn_lshift'
> /usr/local/lib/libntl.a(lip.o): In function `_ntl_gsdiv(void*, long, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1850: undefined reference to`__gmpn_divrem_1'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1848: undefined reference to `__gmpn_rshift'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_gsmod(void_, long)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1915: undefined reference to `__gmpn_mod_1'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_gdiv(void_, void_, void__, void__)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:1989: undefined reference to `__gmpn_tdiv_qr'
> /usr/local/lib/libntl.a(lip.o): In function`gadd_mul_many':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:4662: undefined reference to `__gmpn_addmul_1'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_gsqrt(void_, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:2105: undefined reference to `__gmpn_sqrtrem'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_gsqrts(long)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:2131: undefined reference to `__gmpn_sqrtrem'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_ggcd(void_, void_, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:2187: undefined reference to `__gmpn_gcd'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:2185: undefined reference to`__gmpn_gcd'
> /usr/local/lib/libntl.a(lip.o): In function `_ntl_gexteucl(void*, void**, void*, void**, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:2536: undefined reference to`__gmpn_gcdext'
> /usr/local/lib/libntl.a(lip.o): In function `_ntl_ginv(void*, void*, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:2652: undefined reference to`__gmpn_gcdext'
> /usr/local/lib/libntl.a(lip.o): In function `_ntl_gaorsmul_1(void*, long, long, void**)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:5983: undefined reference to`__gmpn_addmul_1'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:5992: undefined reference to `__gmpn_mul_1'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:6009: undefined reference to`__gmpn_submul_1'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:6044: undefined reference to `__gmpn_mul_1'
> /usr/local/lib/libntl.a(lip.o): In function`_ntl_general_rem_one_struct_apply(void_, long, _ntl_general_rem_one_struct_)':
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:6209: undefined reference to `__gmpn_mod_1'
> /home/user/tools/git/white-box-crypto/ph4r05/Whitebox-crypto-AES-0.4/ntl-9.9.1/src/g_lip_impl.h:6209: undefined reference to`__gmpn_mod_1'
> collect2: error: ld returned 1 exit status
> CMakeFiles/main.dir/build.make:365: recipe for target 'main' failed
> make[2]: **\* [main] Error 1
> CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/main.dir/all' failed
> make[1]: **\* [CMakeFiles/main.dir/all] Error 2
> Makefile:76: recipe for target 'all' failed
> make: **\* [all] Error 2

Any ideas or help of this issue? Thanks in advance.

**Comment by 201312201401019** [comment]
you should use NTL6.0.0

**Comment by ph4r05** [comment]
any progress on this?

**Comment by ph4r05** [comment]
pls check if you have all dependencies installed. 
You can also check the dependencies in travis - the build works fine there. There may be something missing. 

In your case it seems like GMP library.

Maybe try: https://unix.stackexchange.com/questions/265239/how-to-install-a-custom-gmp-lib-for-just-one-user

**Comment by ph4r05** [comment]
Cannot replicate, no updates on this, I am closing the issue
