### ISSUE TITLE
when i use it by vs2013 i  can not understand this problem

### ISSUE THREAD

**Issue by 201312201401019** [ph4r05/Whitebox-crypto-AES#13]
error C2440: “初始化”: 无法从“const int *”转换为“const int (&)[16]”    E:\wbaes\BGEAttack.cpp  66  1   main

**Comment by ph4r05** [comment]
I am sorry but this issue is very short in details and I don see how can I help you with this.

I do not support VisualStudio - I don't have that platform. As a workaround try using something with native CMake support like Clion.
