### ISSUE TITLE
WBAESGenerator::load(const char * filename, WBAES * aes, ExtEncoding * extCoding) throws boost::archive::archive_exception

### ISSUE THREAD

**Issue by veawor** [ph4r05/Whitebox-crypto-AES#14]
I've made 2 test cases at [here](https://github.com/veawor/Whitebox-crypto-AES/blob/master/test/WBAes.cpp). And TEST(WBAES, GenerateKey) wosk as expected, but always fails to load serialized key in TEST(WBAES, EncDec) with the exception. And the error message is input stream error.

**Comment by PratikGajera** [comment]
Dear veawor,

Thank you for made 2 test cases, but how can implements in executible code.Can you provides demo this.

**Comment by veawor** [comment]
I've commited my VC141 projects and dependencies at https://github.com/veawor/Whitebox-crypto-AES/commit/bab59efaa58220f8fa7ac2dc6985e62f6587e2fd for your reference. And the executable code is put at test/wbaes_test.cpp

**Comment by PratikGajera** [comment]
Dear veawor,

when I building WBAes.cpp wbaes_test.cpp source code, getting error fatal error: gtest/gtest.h: No such file or directory. Please provides a solution of this error.

**Comment by veawor** [comment]
@PratikGajera I use googletest for unit test. I've forked googletest and add vc141 projects. You can find it at ext/ Or you can refer to https://github.com/google/googletest

**Comment by PratikGajera** [comment]
Dear veawor,

Thanks for your response!
I want to use encryption/decryption function in to my C++ source code on linux platform.But I unable to find out encryption/decryption function from given code.Can you provides demo code in which can simply use encrypt/decrypt function.

**Comment by wronso** [comment]
The test case I've made is the demo code to use encrypt/decrypt.

**Comment by veawor** [comment]
@PratikGajera The test I've made is the demo code to encrypt/decrypt.

**Comment by PratikGajera** [comment]
Dear Vwawor,

Thanks for your response!
Successfully, I have run the demo code of main in encrypt/decrypt function. I did encrypt the data, but One issue is, when I am decrypting encrypted data then appending some extra junk data with origional data. Kindly gives the solution that how can remove this issue.

**Comment by PratikGajera** [comment]
Dear Vwawor

Currently we are using key table file while we call encrypt/decrypt function, but we want to do that keytable file data hardcoded(like in form of array or string) into the my application instaed of load keytable file externally. So What changes should be made in the given code.

Currently:
generator.load("X:/key.bin", wbaes.get(), &coding);

I want to change like that:
generator.load({string or array data}, wbaes.get(), &coding);

**Comment by ph4r05** [comment]
Thanks all for the support and contributions.

I made some significant changes - all works now with gtest and travis. Pls check if there is still archive exception.

Thanks!

**Comment by ph4r05** [comment]
Due to lack of activity, I am closing the issue. I might reopen on new update,
