### ISSUE TITLE
Unable to find the requested Boost libraries

### ISSUE THREAD

**Issue by PratikGajera** [ph4r05/Whitebox-crypto-AES#17]
When i run the $ cmake -DCMAKE_BUILD_TYPE=Debug .. command on ubuntu 14.04 LTS system then will get the following error.

HOME: /home/test
NTL_INCLUDE_PATH: /home/test/ntl/include
NTL_LIB: /home/test/ntl/lib/libntl.a
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:52 (find_package)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/test/Whitebox_crypto/Whitebox-crypto-AES
   used as include directory in directory /home/test/Whitebox_crypto/Whitebox-crypto-AES

-- Configuring incomplete, errors occurred!
See also "/home/test/Whitebox_crypto/Whitebox-crypto-AES/build-debug/CMakeFiles/CMakeOutput.log".

**Comment by ph4r05** [comment]
It says "Unable to find the requested Boost libraries." 

do you have all dependencies installed?

**Comment by PratikGajera** [comment]
Yes, i have alraedy installed all dependencies library.
Problem slovled!!!
Issue was a version of  boost libraries.
