### ISSUE TITLE
Require given code in AES-256 

### ISSUE THREAD

**Issue by PratikGajera** [ph4r05/Whitebox-crypto-AES#20]
Demo code given is by default AES-128 bit, but I require it in AES-256 bit. So What changes should be made in the given code which can make the AES-128 to AES-256 bit.

**Comment by ph4r05** [comment]
This is a rather complicated feature request :)

AES-256 is more complicated to implement, key schedule is a bit different, it has more rounds. This code does not yet support AES-128 and I don't see a way to modify it in a few hours so it works as AES-256.

It has been a while I was doing this so I am not able to tell you exact modifications needed to refactor it to AES-256 off the top of my head. You could do that by studying the following materials and changing key schedule and round function generation:

http://csrc.nist.gov/archive/aes/rijndael/Rijndael-ammended.pdf

https://eprint.iacr.org/2013/104.pdf

https://is.muni.cz/th/325219/fi_m/thesis.pdf
