### ISSUE TITLE
Confusion about BGE Attack

### ISSUE THREAD

**Issue by PratikGajera** [ph4r05/Whitebox-crypto-AES#21]
Dear Owner,

I builded given source code and get two executible file, its name are main and testing, am I right? When I run testing executible file on my terminal, then some calculation start and takes approximately 2 mins to be completed. After end of this process, got to AES secret key which have used in key table generation. So this demo example is BGE attack, right? It means that attacker can be easily extract secret key from the key table. So how can make secured whitebox cryptograhy. Please help me on my confusion, because I want to use this library in my application.

**Comment by perror** [comment]
> So how can make secured whitebox cryptography ?

This is the one million dollars question... nobody knows yet. All the whitebox schema attempts have been broken till now.

**Comment by PratikGajera** [comment]
I have one key table file and want to be extract secret key from it. If you have this kind of sample code for BGE Attack, kindly provide me the same or could you guide me in making one. I want to look for Whitebox Cryptography streangth.

**Comment by PratikGajera** [comment]
I have one key table file and want to be extract secret key from it. If you have this kind of sample code for BGE Attack, kindly provide me the same or could you guide me in making one. I want to look for Whitebox Cryptography streangth.

**Comment by ph4r05** [comment]
This issue is not related to the code itself, closing.
