### ISSUE TITLE
32 bytes key size supported?

### ISSUE THREAD

**Issue by PratikGajera** [ph4r05/Whitebox-crypto-AES#22]
I have used given code for encryption/decryption with 16 bytes key size and it work fine. But, I want to use it with 32 bytes key size and it for I changed the key size 16 to 32 bytes. After that I have been verified between encrypt function using whitebox and decrypt function using online tool and openssl API. But decrypted data is not same as plain data so it is not work for 32 bytes key size. So I want to confirm that given code is supported in 32 bytes key size or not. If supported, what changes should be do.

**Comment by ph4r05** [comment]
Hi!,

I think we already had exactly this kind of conversation in https://github.com/ph4r05/Whitebox-crypto-AES/issues/20

The AES-128 is only supported now, AES-256 with 32 bytes key is not implemented.
For 256bit you would have to change key schedule and number of rounds.

See the linked issue for more information. 

Closing.
