### ISSUE TITLE
Variables do not take the preference set by the user.

### ISSUE THREAD

**Issue by igorcoroli** [ph4r05/Whitebox-crypto-AES#24]
When the user "true" sets the randomKey and decrypt options are not applied in the code.

SOLUTION:
Line 90:
("create-random", po :: value <bool> () -> default_value (false) -> implicit_value (false), "Create tables with random key")

Change:
("create-random", po :: value <bool> () -> default_value (randomKey) -> implicit_value (randomKey), "Create tables with random key")

Line 93:
("decrypt", po::value<bool>()->default_value(false)->implicit_value(false), "Should perfom encryption or decryption")

Change:
("decrypt",        po::value<bool>()->default_value(decrypt)->implicit_value(decrypt), "Should perfom encryption or decryption")

**Comment by ph4r05** [comment]
Hi! Thanks for the contribution.

But this particular form of code change suggestions is rather unfortunate. Please consider using pull request next time.
