### ISSUE TITLE
Ques need help

### ISSUE THREAD

**Issue by wxk6b1203** [ph4r05/Whitebox-crypto-AES#28]
I am taking an investigation on your code to continue my research. I have some questions need help. Cause of some magic problems, I failed to compile the code. I hope you can give me some hints, thanks!

1. What is the purpose of using random function at line 374 in file `MixingBijections.cpp`
```c++
int generateMixingBijection(mat_GF2& RES, int t, int p) {
// ...
    tmp = phrand() % pBlocksInM;		// current row
    for(i=p*tmp,k=0; k<p; i++, k++){
    for(j=0; j<curT; j++){
        X.put(k,j, M.get(i,j));
    }
}
```
Why **current row** start from here instead of the other position?

I may continue getting into the problems. Sorry for bothering you!.

**Comment by ph4r05** [comment]
I am not answering these as it is long time ago I implemented it. 
All answers can be found in papers I used for implementation:
- http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.59.7710 
- http://dl.acm.org/citation.cfm?id=2041060
