### ISSUE TITLE
  Failed to get the hash for HEAD:

### ISSUE THREAD

**Issue by RanaSaleh** [ph4r05/Whitebox-crypto-AES#32]
Hi everyone:

please during the build i am getting the following error:
 Performing update step for 'googletest'
CMake Error at /Users/ranasaleh/Downloads/Whitebox-crypto-AES-master-3/build-debug/googletest-download/googletest-prefix/tmp/googletest-gitupdate.cmake:25 (message):
  Failed to get the hash for HEAD:

Any idea?
Your help is really apreciated
Thank you

**Comment by ph4r05** [comment]
This may happen if you downloaded ZIP of the repo, maybe try git clonning the repository.
pls reopen if issue persists
