### ISSUE TITLE
the code doesn't has options like pkcs5 and cbc

### ISSUE THREAD

**Issue by WenjieZheng1998** [ph4r05/Whitebox-crypto-AES#34]

**Comment by ph4r05** [comment]
Thanks for reaching out! I am aware, this is pure AES building block. I do not plan adding padding and modes of operation.

**Comment by WenjieZheng1998** [comment]
> Thanks for reaching out! I am aware, this is pure AES building block. I do not plan adding padding and modes of operation.

I run your recongnised code 

> Thanks for reaching out! I am aware, this is pure AES building block. I do not plan adding padding and modes of operation.

I have run code in your example but the result of comparation between the two files is different

**Comment by WenjieZheng1998** [comment]
diff /tmp/aes-table /tmp/aes-table.dec
i get result that the two files is different

**Comment by ph4r05** [comment]
btw the code has cbc and pkcs5 options - pls check readme.

Also, I migrated to github-actions, tests are passing.
