### ISSUE TITLE
External encodings don't work with serialization

### ISSUE THREAD

**Issue by doegox** [ph4r05/Whitebox-crypto-AES#6]
External encodings are not serialized when saving tables and are regenerated randomly whenever tables are loaded.
So currently --extEnc=1 and --create-table/--load-tables are incompatible options.
It would be nice to support serialization with external encodings.
Thanks.
Phil

**Comment by ph4r05** [comment]
Thanks for reporting! I will take a look.

**Comment by ph4r05** [comment]
Thanks for suggestion, you are right, it would be nice.

This is my reasoning: ExtEncoding can be serialized to a file together with WBAES. WBAES was generated with ExtEncoding embedded and it expects input data to be already processed by ExtEncoding. To keep things separated, WBAES should not "know" about ExtEncoding that it used with it, so the serialization should not be done by WBAES object itself, to keep it simple, to abstract from generator logic and so on.

So I've added serialization to the WBAESGenerator, which serializes WBAES and ExtEncoding to the same file. When using main, it uses now this new way of serialization.
