### ISSUE TITLE
Don't display default AES key when loading from tables

### ISSUE THREAD

**Issue by doegox** [ph4r05/Whitebox-crypto-AES#8]
When using ```--load-tables``` it still prints the message about AES key, therefore showing the default key:

```
AES key to use: 2b 7e 15 16 28 ae d2 a6 ab f7 15 88 09 cf 4f 3c 
```

A bit cosmetic but this should be masked to avoid confusion IMHO.

**Comment by ph4r05** [comment]
Thanks!
fixed
